Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end
    config.vm.define "vsaltelS" do |control|
        control.vm.hostname = "vsaltelS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provision :shell, path: "scripts/install.sh"
    end
end
