Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "2"
    end
    config.vm.define "vsaltel-gitlab" do |control|
        control.vm.hostname = "vsaltel-gitlab"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provision :shell, path: "scripts/install.sh"
    end
end
